version: "3"
services:
  # Sample Go application producing counter metrics.
  prom-counter:
    container_name: prom-counter
    build:
      context: prom-counter
    restart: always
  # The Prometheus server:
  prometheus:
    image: prom/prometheus@sha256:508729e0e2d18e11fd742a5a5ca70e557b940a93948c3c95fd0123a6fd538b69
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  # OpenTelemetry Collector
  otelcollector:
    image: otel/opentelemetry-collector-contrib-dev:latest@sha256:3234c09994d02460886c5b776ea0ca3ed0b5b832d31518bdf596e2e788122f44
    container_name: otelcollector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - prometheus
